apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodtruck-deployment
  labels:
    app: foodtruck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodtruck
  template:
    metadata:
      labels:
        app: foodtruck
    spec:
      containers:
        - name: foodtruck
          image: sharathwork99/sharath-food-truck:jenkins
          imagePullPolicy: Always        # ðŸ”´ IMPORTANT for CI/CD
          ports:
            - containerPort: 5000        # Flask/Gunicorn port inside container
