apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sft-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: sharath-food-truck.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sharath-food-truck
                port:
                  number: 80
