apiVersion: v1
kind: Service
metadata:
  name: foodtruck-service
spec:
  selector:
    app: foodtruck
  type: NodePort                  # You can change to ClusterIP later if you want only Ingress
  ports:
    - port: 80                    # Service port inside cluster
      targetPort: 5000            # Container port (Flask/Gunicorn)
      nodePort: 30080             # NodePort on your laptop (optional, for direct access)
